### ISSUE TITLE
Issue on create Event Attendee validation check

### ISSUE THREAD

**Issue by HowardYaw** [Five-Fishes/Club-Management-Spring-Server#23]
should we have a close registration date filed for an event?
for now event is closed for registration at the start date of event

**Comment by junzai97** [comment]
Because the current add attendee is done by the management team, I'm thinking of maybe we should remove the event date validation? So they are still allowed to add/modify the attendee list after that. 

Or maybe instead of using a date to validate, maybe we can have a flag that need to be set manually by the management team?  Once they set the adding attendee flag to "CLOSED", then the event can no longer add with attendee

**Comment by junzai97** [comment]
The issue is closed unintentionally.

**Comment by kachun333** [comment]
I don't think we need a close registration date.
We can think about it only if the end-user request this feature or the business wants it.

just keep it as it is now is good enough.

**Comment by HowardYaw** [comment]
Create a new table (event_registration_closing_criteria) link to event table
Having a service class to implement the closing criteria logic
Fields:
- eventId
- maxAttendees
- closingDate

**Comment by LUXIANZE** [comment]
The new Table (event_registration_closing_criteria) is created such that it provides a mechanism to control what are the fields to be considered when a new registration should be allowed.

- When we have a new criteria to take care of while determining whether should the registration allowed, we can add a column if it is not already exist (example: closingDate)
- Based on the latest business logic/ certain requirements, we implement a service such that it considers only the criteria that are essential to determine whether should a new registration be allowed

**Comment by HowardYaw** [comment]
suggestion with a forceClose column for event_registration_closing_criteria
- Event Head, CC Head, Vice CC Head click on close registration now in FE
