### ISSUE TITLE
What is Debt table?

### ISSUE THREAD

**Issue by kachun333** [Five-Fishes/Club-Management-Spring-Server#40]
# Motivation
The motivation of `Debt` table is to cater the scenario when an EventAttendee hasn't pay for their participation fee.

_that is why `event_participant_id` is there_

# Current Implementation
![image](https://user-images.githubusercontent.com/34387770/99879135-98f6ef80-2bbf-11eb-9289-238e97990824.png)

# Logical Flow
After a participant register, 
1. a record will be inserted into `Debt` table (the status will be `OPEN`)

After a participant have pay,
1. a receipt will be generated
2. a record will be inserted into `Receipt` table
3. update the receiptId in the `Debt` table
4. change the status the record in `Debt` as `COLLECTED`

# Question
1. can we change the name of table? from `Debt` -> `EventAttendeePayment`, because the name "Debt" has ambiguity.
2. should the `event_participant_id ` column change name to `event_attendee_id`
3. before the payment is made, the `receipt_storage_Id` is `null`?
4. after the payment is made (status is `COLLECTED`), will we insert a new record into the `transaction` table? 
5. In the financial report, since we will need to present the totalIncome and totalExpenses. Do we need to include this `Debt` table into consideration when calculating the  totalIncome and totalExpenses. (Debt that is not in `COLLECTED` status will not include in calculation?

**Comment by HowardYaw** [comment]
1. Create this table as debt is because we can use for other scenarios when we need to have a charge to the user which might not be a event fee.
2. Ya you are right, we should change the column name
3. Maybe we can remove the receipt_storage_id. And remove relationship between receipt and debt. See 4 for more details
4. I think we should have transactions record after we collected the debt from user.
5. If we approve for 4 which create a new record of transactions when user pay their debt, then financial report will only need to get from transactions table

**Comment by kachun333** [comment]
I'm fine with most of the points, except for point number 1.

If this table is not only used for the event fee. Then the `event_attendee_id` column might not be relevant already. And thus there might be scenarios where we just have to put `null` for that column

**Comment by HowardYaw** [comment]
Maybe need to replace with user_id and event_id?
@LUXIANZE can u recall anything about this table? Debt is only for event?

**Comment by HowardYaw** [comment]
Debt Table will keep
changes on this table:
- use event_attendee_id
- remove receipt_storage_id

New transactions will be inserted when debt status changed (COLLECTED)

Encourage admin to request all event attendee to register in app before payment
